add_lunch_combo commotio_toro-userdebug
add_lunch_combo commotio_maguro-userdebug
add_lunch_combo commotio_toroplus-userdebug
add_lunch_combo commotio_toro-user
add_lunch_combo commotio_maguro-user
add_lunch_combo commotio_toroplus-user
add_lunch_combo commotio_grouper-user
