#!/system/bin/sh
# DHO

#Disable color-control safety + color presents
echo "0" > /sys/class/misc/colorcontrol/safety_enabled
echo "-6 0 8" > /sys/class/misc/colorcontrol/v1_offset
echo "8" > /sys/class/misc/colorcontrol/blue_v1_offset
echo "0" > /sys/class/misc/colorcontrol/green_v1_offset
echo "-6" > /sys/class/misc/colorcontrol/red_v1_offset
echo "2204318071 2004318071 2654318071" > /sys/class/misc/colorcontrol/multiplier
echo "6" > /sys/devices/platform/omapdss/manager0/gamma

# Nuking run once scripts
 busybox mount -o rw,remount /system
 rm /system/etc/init.d/01dhotheory
 #! /bin/rm -f
 busybox mount -o ro,remount /system