#!/system/bin/sh
# DroidTheory + DHO

# Kernel Tweaks
#
busybox sysctl -w kernel.panic=0
busybox sysctl -w kernel.panic_on_oops=1
busybox sysctl -w kernel.msgmni=2048
busybox sysctl -w kernel.msgmax=64000
busybox sysctl -w kernel.shmmax=268435500
busybox sysctl -w kernel.sem=500,512000,64,2048
busybox sysctl -w kernel.hung_task_timeout_secs=0
busybox sysctl -w kernel.sched_latency_ns=5000000; #600000
busybox sysctl -w kernel.sched_min_granularity_ns=1000000; #400000
busybox sysctl -w kernel.sched_wakeup_granularity_ns=1000000
busybox sysctl -w kernel.sched_child_runs_first=0
busybox sysctl -w kernel.threads-max=525810

# Battery Tweaks
busybox sysctl -w kernel.random.write_wakeup_threshold=256
busybox sysctl -w kernel.random.read_wakeup_threshold=128

# Enable KSM
#
echo 1 > /sys/kernel/mm/ksm/run
echo 1200 > /sys/kernel/mm/ksm/sleep_millisecs
echo 256 > /sys/kernel/mm/ksm/pages_to_scan

# disable logger - (comment and reboot for logcat)
# rm /dev/log/main

# Breaking the lease
# Prime Directive
echo "15" > /proc/sys/fs/lease-break-time

exit 0