#!/system/bin/sh
# DroidTheory + DHO + Vanir

mount -o remount,rw rootfs /

# enable sysctl tweaks
sysctl -p /system/etc/sysctl.conf

# HyperTh3ory
busybox rm -f /cache/*.apk
busybox rm -f /cache/*.tmp
busybox rm -f /data/dalvik-cache/*.apk
busybox rm -f /data/dalvik-cache/*.tmp

busybox sysctl -w vm.overcommit_memory=1
busybox sysctl -w vm.page-cluster=3
busybox sysctl -w vm.drop_caches=3
echo "1" > /proc/sys/vm/laptop_mode

# Battery
busybox sysctl -w vm.dirty_expire_centisecs=750
busybox sysctl -w vm.dirty_writeback_centisecs=1500

# iostats disabling
for i in `find /sys/devices/platform -name iostats`; do echo "0" > $i; done


mount -o remount,ro rootfs /

exit 0