#!/system/bin/sh
# DroidTheory + DHO + Vanir

sync
mount -o remount,rw /system

# enable sysctl tweaks
sysctl -p /system/etc/sysctl.conf

# HyperTh3ory
busybox rm -f /cache/*.apk
busybox rm -f /cache/*.tmp
busybox rm -f /data/dalvik-cache/*.apk
busybox rm -f /data/dalvik-cache/*.tmp

busybox sysctl -w vm.overcommit_memory=1
busybox sysctl -w vm.page-cluster=3
busybox sysctl -w vm.drop_caches=3
echo "1" > /proc/sys/vm/laptop_mode

# SD Card Speed Boost
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
  echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

# Vibration if used
echo 1498 > /sys/vibe/pwmduty

# Battery
busybox sysctl -w vm.dirty_expire_centisecs=750
busybox sysctl -w vm.dirty_writeback_centisecs=1500

# RQ_Affinity
for b in /sys/block/*; do echo 1 > $b/queue/rq_affinity; done

# iostats disabling
for i in `find /sys/devices/platform -name iostats`; do echo "0" > $i; done 

# Optimize Vm
if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
	echo "10" > /proc/sys/vm/vfs_cache_pressure
fi

if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
	echo "500" > /proc/sys/vm/dirty_expire_centisecs
fi

if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
	echo "1000" > /proc/sys/vm/dirty_writeback_centisecs
fi

if [ -e /proc/sys/vm/dirty_ratio ]; then
	echo "90" > /proc/sys/vm/dirty_ratio
fi

if [ -e /proc/sys/vm/dirty_background_ratio ]; then
	echo "45" > /proc/sys/vm/dirty_background_ratio
fi

if [ -f "\$i" ]; then
	sync;
	echo "cfq" > \$i;
fi

sync
mount -o remount,ro /system
