PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/commotio_bacon.mk \
    $(LOCAL_DIR)/commotio_deb.mk \
    $(LOCAL_DIR)/commotio_d2lte.mk \
    $(LOCAL_DIR)/commotio_d710.mk \
    $(LOCAL_DIR)/commotio_d800.mk \
    $(LOCAL_DIR)/commotio_d801.mk \
    $(LOCAL_DIR)/commotio_d802.mk \
    $(LOCAL_DIR)/commotio_dlx.mk \
    $(LOCAL_DIR)/commotio_e980.mk \
    $(LOCAL_DIR)/commotio_falcon.mk \
    $(LOCAL_DIR)/commotio_find5.mk \
    $(LOCAL_DIR)/commotio_find7.mk \
    $(LOCAL_DIR)/commotio_flo.mk \
    $(LOCAL_DIR)/commotio_gee.mk \
    $(LOCAL_DIR)/commotio_geeb.mk \
    $(LOCAL_DIR)/commotio_grouper.mk \
    $(LOCAL_DIR)/commotio_hammerhead.mk \
    $(LOCAL_DIR)/commotio_hlte.mk \
    $(LOCAL_DIR)/commotio_i605.mk \
    $(LOCAL_DIR)/commotio_i9300.mk \
    $(LOCAL_DIR)/commotio_i9305.mk \
    $(LOCAL_DIR)/commotio_jewel.mk \
    $(LOCAL_DIR)/commotio_jflte.mk \
    $(LOCAL_DIR)/commotio_m7att.mk \
    $(LOCAL_DIR)/commotio_m7spr.mk \
    $(LOCAL_DIR)/commotio_m7tmo.mk \
    $(LOCAL_DIR)/commotio_m7ul.mk \
    $(LOCAL_DIR)/commotio_m7vzw.mk \
    $(LOCAL_DIR)/commotio_m8.mk \
    $(LOCAL_DIR)/commotio_manta.mk \
    $(LOCAL_DIR)/commotio_maguro.mk \
    $(LOCAL_DIR)/commotio_mako.mk \
    $(LOCAL_DIR)/commotio_maserati.mk \
    $(LOCAL_DIR)/commotio_mondrianwifi.mk \
    $(LOCAL_DIR)/commotio_moto_msm8960.mk \
    $(LOCAL_DIR)/commotio_moto_msm8960_jbbl.mk \
    $(LOCAL_DIR)/commotio_moto_msm8960dt.mk \
    $(LOCAL_DIR)/commotio_n1.mk \
    $(LOCAL_DIR)/commotio_p880.mk \
    $(LOCAL_DIR)/commotio_pollux.mk \
    $(LOCAL_DIR)/commotio_pollux_windy.mk \
    $(LOCAL_DIR)/commotio_quincyatt.mk \
    $(LOCAL_DIR)/commotio_quincytmo.mk \
    $(LOCAL_DIR)/commotio_t0lte.mk \
    $(LOCAL_DIR)/commotio_tf700.mk \
    $(LOCAL_DIR)/commotio_tf701.mk \
    $(LOCAL_DIR)/commotio_tilapia.mk \
    $(LOCAL_DIR)/commotio_toro.mk \
    $(LOCAL_DIR)/commotio_toroplus.mk \
    $(LOCAL_DIR)/commotio_v500.mk \
    $(LOCAL_DIR)/commotio_vigor.mk \
    $(LOCAL_DIR)/commotio_vs980.mk \
    $(LOCAL_DIR)/commotio_yuga.mk
