PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/commotio_deb.mk \
    $(LOCAL_DIR)/commotio_d2att.mk \
    $(LOCAL_DIR)/commotio_d2spr.mk \
    $(LOCAL_DIR)/commotio_d2tmo.mk \
    $(LOCAL_DIR)/commotio_d2vzw.mk \
    $(LOCAL_DIR)/commotio_d710.mk \
    $(LOCAL_DIR)/commotio_d800.mk \
    $(LOCAL_DIR)/commotio_d801.mk \
    $(LOCAL_DIR)/commotio_d802.mk \
    $(LOCAL_DIR)/commotio_dlx.mk \
    $(LOCAL_DIR)/commotio_e980.mk \
    $(LOCAL_DIR)/commotio_flo.mk \
    $(LOCAL_DIR)/commotio_gee.mk \
    $(LOCAL_DIR)/commotio_geeb.mk \
    $(LOCAL_DIR)/commotio_grouper.mk \
    $(LOCAL_DIR)/commotio_hammerhead.mk \
    $(LOCAL_DIR)/commotio_hlte.mk \
    $(LOCAL_DIR)/commotio_i605.mk \
    $(LOCAL_DIR)/commotio_i9300.mk \
    $(LOCAL_DIR)/commotio_i9305.mk \
    $(LOCAL_DIR)/commotio_jewel.mk \
    $(LOCAL_DIR)/commotio_m7att.mk \
    $(LOCAL_DIR)/commotio_m7spr.mk \
    $(LOCAL_DIR)/commotio_m7tmo.mk \
    $(LOCAL_DIR)/commotio_m7ul.mk \
    $(LOCAL_DIR)/commotio_m7vzw.mk \
    $(LOCAL_DIR)/commotio_manta.mk \
    $(LOCAL_DIR)/commotio_maguro.mk \
    $(LOCAL_DIR)/commotio_mako.mk \
    $(LOCAL_DIR)/commotio_maserati.mk \
    $(LOCAL_DIR)/commotio_p880.mk \
    $(LOCAL_DIR)/commotio_pollux.mk \
    $(LOCAL_DIR)/commotio_pollux_windy.mk \
    $(LOCAL_DIR)/commotio_quincyatt.mk \
    $(LOCAL_DIR)/commotio_quincytmo.mk \
    $(LOCAL_DIR)/commotio_jfltevzw.mk \
    $(LOCAL_DIR)/commotio_jflteatt.mk \
    $(LOCAL_DIR)/commotio_jfltecan.mk \
    $(LOCAL_DIR)/commotio_jfltecri.mk \
    $(LOCAL_DIR)/commotio_jfltespr.mk \
    $(LOCAL_DIR)/commotio_jfltetmo.mk \
    $(LOCAL_DIR)/commotio_jflteusc.mk \
    $(LOCAL_DIR)/commotio_jfltexx.mk \
    $(LOCAL_DIR)/commotio_t0lteatt.mk \
    $(LOCAL_DIR)/commotio_t0ltetmo.mk \
    $(LOCAL_DIR)/commotio_tf700.mk \
    $(LOCAL_DIR)/commotio_tilapia.mk \
    $(LOCAL_DIR)/commotio_toro.mk \
    $(LOCAL_DIR)/commotio_toroplus.mk \
    $(LOCAL_DIR)/commotio_vigor.mk \
    $(LOCAL_DIR)/commotio_vs980.mk \
    $(LOCAL_DIR)/commotio_xt907.mk \
    $(LOCAL_DIR)/commotio_xt1060.mk \
    $(LOCAL_DIR)/commotio_yuga.mk
