#!/system/xbin/bash
# Nice Tweaks
# Nuclearmistake, PrimeDirective, DHO, and Sonicxml

#DEBUG=1

db()
{
    [ -z $DEBUG ] && return 0
    echo "$*"
}
smartrenice()
{
    for pid in `pgrep -f $1`; do
        [ $pid ] && db "RENICING $1 to $2" && renice $2 $pid
    done
    return 0
}
smartionice()
{
    for pid in `pgrep -f $1`; do
        [ $pid ] && db "IONICING $1 to $2 $3" && ionice $pid $2 $3 >& /dev/null
    done
    return 0
}
for kb in "android.inputmethod.latin" "pckeyboard" "swype" "swiftkey"; do smartrenice $kb -5; done
for browser in "dolphin" "com.android.browser" "chrome"; do smartrenice $browser -4; done
smartrenice com.android.phone -12
smartrenice com.android.systemui -11
smartrenice launcher -10
smartrenice com.google.android.googlequicksearchbox -3
smartrenice com.google.android.apps.googlevoice -1
smartionice com.android.gallery be 0
smartionice com.google.android.music rt 1
exit 0