#!/bin/bash
#
# Squish a Vanir otapackage for distribution
# credit for original version: CM
#

export ANDROID_BUILD_TOP=$ANDROID_BUILD_TOP

. $ANDROID_BUILD_TOP/vendor/vanir/tools/functions

QUIET=-q

# Determine what to name the new signed package
GOOROM=`sed -n -e'/ro\.goo\.rom/s/^.*=//p' $OUT/system/build.prop`
GOOVERSION=`sed -n -e'/ro\.goo\.version/s/^.*=//p' $OUT/system/build.prop`
MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $OUT/system/build.prop`
OUTVERSION=B"$GOOVERSION"-"$GOOROM"
OUTFILE=$OUT/$OUTVERSION.zip
ln -f $OTA_PACKAGE_PATH $OUTFILE

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`

$MD5 $img >$img.md5sum
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo ""
echo -e $CL_CYN"Package complete:"$CL_MAG" $OUTFILE"$CL_RST
echo -e $CL_BLU"Package Size: "$CL_YLW"$ZIPSIZE "
echo -e $CL_CYN"md5:"$CL_MAG" $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
echo ""
)

exit 0
